### ISSUE TITLE
httpbin problem

### ISSUE THREAD

**Issue by cascha42** [3zuli/esp_internet_alarm#1]
hey,
thank you for this nice project!
i cannot GET data from the httpbin site.
also with other machines i cannot ping this host..

do you know something about that?

thank you
c_ascha

**Comment by 3zuli** [comment]
Hi, 
httpbin.org works fine from my computer. As a first step, try to use some different domain (google.com should definitely work). Also, in the past had issues with some modules not being able to connect to one of my WiFi networks, maybe that could be the problem? Let me know if you figure something out.

Adam
